baseURL = 'https://kkbt0.github.io/Hugo-Landscape/'
languageCode = 'zh-cn'
hasCJKLanguage = true
title = 'Landscape'
theme = '../..'


[params]
[params.banner]
title = 'Landscape'
subtitle = '我们的征途是星辰大海！'

[params.author]
name = '恐咖兵糖'
email = ''

[params.comment]
enable = true
provider = "Mastodon"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5